//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4952
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=2.0.50727.1432.
// 
namespace GenerateSpec.Generator {
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.sifassociation.org/sifSpecificationGenerator/1.0")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://www.sifassociation.org/sifSpecificationGenerator/1.0", IsNullable=false)]
    public partial class sifSpecificationGeneratorConfig {
        
        private sifSpecificationGeneratorConfigGlobalSettings globalSettingsField;
        
        private sifSpecificationGeneratorConfigHtmlDocument[] htmlDocumentsField;
        
        private sifSpecificationGeneratorConfigWebServiceDocument[] webServiceDocumentsField;
        
        private sifSpecificationGeneratorConfigXsdDocument[] xsdDocumentsField;
        
        /// <remarks/>
        public sifSpecificationGeneratorConfigGlobalSettings globalSettings {
            get {
                return this.globalSettingsField;
            }
            set {
                this.globalSettingsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("htmlDocument", IsNullable=false)]
        public sifSpecificationGeneratorConfigHtmlDocument[] htmlDocuments {
            get {
                return this.htmlDocumentsField;
            }
            set {
                this.htmlDocumentsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("webServiceDocument", IsNullable=false)]
        public sifSpecificationGeneratorConfigWebServiceDocument[] webServiceDocuments {
            get {
                return this.webServiceDocumentsField;
            }
            set {
                this.webServiceDocumentsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("xsdDocument", IsNullable=false)]
        public sifSpecificationGeneratorConfigXsdDocument[] xsdDocuments {
            get {
                return this.xsdDocumentsField;
            }
            set {
                this.xsdDocumentsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.sifassociation.org/sifSpecificationGenerator/1.0")]
    public partial class sifSpecificationGeneratorConfigGlobalSettings {
        
        private string inputDocumentField;
        
        private string sifNamespaceField;
        
        private string localizationCodeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="normalizedString")]
        public string inputDocument {
            get {
                return this.inputDocumentField;
            }
            set {
                this.inputDocumentField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="normalizedString")]
        public string sifNamespace {
            get {
                return this.sifNamespaceField;
            }
            set {
                this.sifNamespaceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="normalizedString")]
        public string localizationCode {
            get {
                return this.localizationCodeField;
            }
            set {
                this.localizationCodeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.sifassociation.org/sifSpecificationGenerator/1.0")]
    public partial class sifSpecificationGeneratorConfigHtmlDocument {
        
        private bool singleDocumentField;
        
        private string rootDocumentFileNameField;
        
        private string rootTitleField;
        
        private sifSpecificationGeneratorConfigHtmlDocumentDocumentType documentTypeField;
        
        /// <remarks/>
        public bool singleDocument {
            get {
                return this.singleDocumentField;
            }
            set {
                this.singleDocumentField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="normalizedString")]
        public string rootDocumentFileName {
            get {
                return this.rootDocumentFileNameField;
            }
            set {
                this.rootDocumentFileNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="normalizedString")]
        public string rootTitle {
            get {
                return this.rootTitleField;
            }
            set {
                this.rootTitleField = value;
            }
        }
        
        /// <remarks/>
        public sifSpecificationGeneratorConfigHtmlDocumentDocumentType documentType {
            get {
                return this.documentTypeField;
            }
            set {
                this.documentTypeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.sifassociation.org/sifSpecificationGenerator/1.0")]
    public enum sifSpecificationGeneratorConfigHtmlDocumentDocumentType {
        
        /// <remarks/>
        DataModel,
        
        /// <remarks/>
        Infrastructure,
        
        /// <remarks/>
        Combined,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.sifassociation.org/sifSpecificationGenerator/1.0")]
    public partial class sifSpecificationGeneratorConfigWebServiceDocument {
        
        private bool singleDocumentField;
        
        private string rootDocumentFileNameField;
        
        /// <remarks/>
        public bool singleDocument {
            get {
                return this.singleDocumentField;
            }
            set {
                this.singleDocumentField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="normalizedString")]
        public string rootDocumentFileName {
            get {
                return this.rootDocumentFileNameField;
            }
            set {
                this.rootDocumentFileNameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.sifassociation.org/sifSpecificationGenerator/1.0")]
    public partial class sifSpecificationGeneratorConfigXsdDocument {
        
        private string xsdTitleField;
        
        private bool diagramField;
        
        private bool isDataModelXsdField;
        
        private bool isServiceBodyXsdField;
        
        private bool singleSchemaField;
        
        private bool annotateField;
        
        private bool listWithKeyConstraintsField;
        
        private bool isSifMessage2XsdField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="normalizedString")]
        public string xsdTitle {
            get {
                return this.xsdTitleField;
            }
            set {
                this.xsdTitleField = value;
            }
        }
        
        /// <remarks/>
        public bool diagram {
            get {
                return this.diagramField;
            }
            set {
                this.diagramField = value;
            }
        }
        
        /// <remarks/>
        public bool isDataModelXsd {
            get {
                return this.isDataModelXsdField;
            }
            set {
                this.isDataModelXsdField = value;
            }
        }
        
        /// <remarks/>
        public bool isServiceBodyXsd {
            get {
                return this.isServiceBodyXsdField;
            }
            set {
                this.isServiceBodyXsdField = value;
            }
        }
        
        /// <remarks/>
        public bool singleSchema {
            get {
                return this.singleSchemaField;
            }
            set {
                this.singleSchemaField = value;
            }
        }
        
        /// <remarks/>
        public bool annotate {
            get {
                return this.annotateField;
            }
            set {
                this.annotateField = value;
            }
        }
        
        /// <remarks/>
        public bool listWithKeyConstraints {
            get {
                return this.listWithKeyConstraintsField;
            }
            set {
                this.listWithKeyConstraintsField = value;
            }
        }
        
        /// <remarks/>
        public bool isSifMessage2Xsd {
            get {
                return this.isSifMessage2XsdField;
            }
            set {
                this.isSifMessage2XsdField = value;
            }
        }
    }
}
